# Generated by Django 3.0.8 on 2020-07-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200729_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, default='/static/img/default.jpg', null=True, upload_to='articles/'),
        ),
    ]
