# Generated by Django 3.0.8 on 2020-07-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200729_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='/static/img/default.jpg', upload_to='articles/'),
        ),
    ]
